import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, User, Sparkles, Loader2, Download, RefreshCw } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

interface Persona {
  name: string;
  age: string;
  occupation: string;
  location: string;
  bio: string;
  goals: string[];
  painPoints: string[];
  preferredChannels: string[];
  quote: string;
}

const MarketingPersonaGenerator = () => {
  const [businessType, setBusinessType] = useState("");
  const [targetAudience, setTargetAudience] = useState("");
  const [industry, setIndustry] = useState("");
  const [product, setProduct] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [persona, setPersona] = useState<Persona | null>(null);

  const generatePersona = async () => {
    if (!businessType || !targetAudience) {
      toast.error("Please fill in at least business type and target audience");
      return;
    }

    setIsGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke('ai-persona-generator', {
        body: { businessType, targetAudience, industry, product }
      });

      if (error) throw error;
      setPersona(data.persona);
      toast.success("Persona generated!");
    } catch (error) {
      console.error("Error generating persona:", error);
      toast.error("Failed to generate persona. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadPersona = () => {
    if (!persona) return;
    
    const content = `
# ${persona.name}
## Marketing Persona

**Age:** ${persona.age}
**Occupation:** ${persona.occupation}
**Location:** ${persona.location}

### Bio
${persona.bio}

### Goals
${persona.goals.map(g => `- ${g}`).join('\n')}

### Pain Points
${persona.painPoints.map(p => `- ${p}`).join('\n')}

### Preferred Channels
${persona.preferredChannels.map(c => `- ${c}`).join('\n')}

### Quote
"${persona.quote}"

---
Generated by KAMROK Marketing Persona Generator
    `.trim();

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.download = `${persona.name.replace(/\s+/g, '-').toLowerCase()}-persona.md`;
    link.href = url;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <Link to="/tools" className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground mb-6">
          <ArrowLeft className="h-4 w-4" />
          Back to Tools
        </Link>

        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-purple-500/20 to-purple-500/5 mb-4">
            <User className="h-8 w-8 text-purple-500" />
          </div>
          <h1 className="text-3xl font-bold mb-2">Marketing Persona Generator</h1>
          <p className="text-muted-foreground">Create detailed buyer personas with AI</p>
        </div>

        <div className="grid md:grid-cols-2 gap-6">
          <Card>
            <CardContent className="p-6 space-y-4">
              <div>
                <Label htmlFor="business" className="mb-2 block">Business Type *</Label>
                <Input
                  id="business"
                  value={businessType}
                  onChange={(e) => setBusinessType(e.target.value)}
                  placeholder="e.g., SaaS startup, Local bakery, Fitness coach"
                />
              </div>

              <div>
                <Label htmlFor="audience" className="mb-2 block">Target Audience *</Label>
                <Textarea
                  id="audience"
                  value={targetAudience}
                  onChange={(e) => setTargetAudience(e.target.value)}
                  placeholder="e.g., Small business owners aged 30-50 who struggle with time management"
                  rows={3}
                />
              </div>

              <div>
                <Label htmlFor="industry" className="mb-2 block">Industry</Label>
                <Select value={industry} onValueChange={setIndustry}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select industry" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="technology">Technology</SelectItem>
                    <SelectItem value="healthcare">Healthcare</SelectItem>
                    <SelectItem value="finance">Finance</SelectItem>
                    <SelectItem value="retail">Retail</SelectItem>
                    <SelectItem value="education">Education</SelectItem>
                    <SelectItem value="hospitality">Hospitality</SelectItem>
                    <SelectItem value="professional-services">Professional Services</SelectItem>
                    <SelectItem value="other">Other</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label htmlFor="product" className="mb-2 block">Product/Service</Label>
                <Input
                  id="product"
                  value={product}
                  onChange={(e) => setProduct(e.target.value)}
                  placeholder="e.g., Project management software"
                />
              </div>

              <Button 
                onClick={generatePersona} 
                disabled={isGenerating || !businessType || !targetAudience}
                className="w-full"
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4 mr-2" />
                    Generate Persona
                  </>
                )}
              </Button>
            </CardContent>
          </Card>

          {persona ? (
            <Card className="border-primary/20">
              <CardContent className="p-6">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-3">
                    <div className="w-12 h-12 rounded-full bg-gradient-to-br from-primary to-purple-500 flex items-center justify-center text-white font-bold text-lg">
                      {persona.name.charAt(0)}
                    </div>
                    <div>
                      <h3 className="font-bold text-lg">{persona.name}</h3>
                      <p className="text-sm text-muted-foreground">{persona.occupation}</p>
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="icon" onClick={generatePersona}>
                      <RefreshCw className="h-4 w-4" />
                    </Button>
                    <Button variant="outline" size="icon" onClick={downloadPersona}>
                      <Download className="h-4 w-4" />
                    </Button>
                  </div>
                </div>

                <div className="flex gap-4 text-sm text-muted-foreground mb-4">
                  <span>{persona.age}</span>
                  <span>•</span>
                  <span>{persona.location}</span>
                </div>

                <p className="text-sm mb-4 italic">"{persona.quote}"</p>

                <div className="space-y-4">
                  <div>
                    <h4 className="font-medium mb-2 text-sm">Bio</h4>
                    <p className="text-sm text-muted-foreground">{persona.bio}</p>
                  </div>

                  <div>
                    <h4 className="font-medium mb-2 text-sm">Goals</h4>
                    <ul className="text-sm text-muted-foreground space-y-1">
                      {persona.goals.map((goal, i) => (
                        <li key={i} className="flex items-start gap-2">
                          <span className="text-green-500">✓</span>
                          {goal}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div>
                    <h4 className="font-medium mb-2 text-sm">Pain Points</h4>
                    <ul className="text-sm text-muted-foreground space-y-1">
                      {persona.painPoints.map((pain, i) => (
                        <li key={i} className="flex items-start gap-2">
                          <span className="text-red-500">✗</span>
                          {pain}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div>
                    <h4 className="font-medium mb-2 text-sm">Preferred Channels</h4>
                    <div className="flex flex-wrap gap-2">
                      {persona.preferredChannels.map((channel, i) => (
                        <span 
                          key={i}
                          className="px-2 py-1 bg-muted text-xs rounded-full"
                        >
                          {channel}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ) : (
            <Card className="flex items-center justify-center min-h-[400px]">
              <CardContent className="text-center p-6">
                <User className="h-16 w-16 mx-auto mb-4 text-muted-foreground/30" />
                <h3 className="font-medium mb-2">No Persona Yet</h3>
                <p className="text-sm text-muted-foreground">
                  Fill in the details and click "Generate Persona" to create your buyer persona.
                </p>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
};

export default MarketingPersonaGenerator;
