import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowDown, ArrowUpRight, Check, CreditCard, Mail, MessageCircle, Plus, Store, UtensilsCrossed } from "lucide-react";
import TakeawayShowcase from "@/components/kamrok/TakeawayShowcase";
import KamrokLayout from "@/components/kamrok/KamrokLayout";
import { CONTACT_PHONE, CONTACT_TEL, LOVABLE_AFFILIATE_URL } from "@/lib/brand";
import "@/styles/takeaway.css";

const DEMO = "https://live-menu-hub-kamrok-remix.lovable.app/";
const FAQ = [
  ["Is Takeaway Hub really commission free?", "KAMROK charges 0% commission on orders through your own Takeaway Hub website. Your payment provider still charges its own processing fees. Your Lovable plan, domain and any extra usage or third-party services are separate. The free template is a DIY starting point; you configure and operate your own site."],
  ["Are there website design or setup fees?", "There is no KAMROK website design fee or setup fee to use the template yourself. Replace the example content and configure your site in your own Lovable account. If you choose to hire KAMROK for custom design, integrations or launch support, that work is quoted separately before it starts."],
  ["What does it cost to launch my own takeaway website?", "Lovable Pro starts at US$25 per month and supports your own domain. You also need a domain name, a payment-provider account if taking online payments, and any extra usage or services your site needs. Currency, taxes and the current plan price are confirmed by Lovable at checkout. Pricing checked October 2026."],
  ["Can I connect Stripe or my existing payment gateway?", "Lovable supports connecting your own Stripe account. Another gateway may be possible if it has a suitable API or hosted checkout, but compatibility and integration work need checking first. Connect your account, configure payments and refunds, and test the complete order journey before going live. Payment processing is not free."],
  ["Can I add WhatsApp, Gmail and more tools?", "Yes. Lovable lists Gmail and WhatsApp Business connectors, alongside tools such as Google Sheets and Google Maps. You can build features around them after connecting the relevant accounts. These are optional additions, not preconfigured services in the template. Provider approvals, permissions, usage limits and fees may apply."],
  ["How does live driver sharing work?", "Owners create individual driver links from delivery orders. Live location sharing requires HTTPS, location permission and an open browser tab on the driver’s device. Stale positions are hidden automatically. If sharing stops, the tracker should not be treated as a current location."],
  ["Will this bring me customers like an ordering marketplace?", "This is your own website, so you bring customers through your Google Business Profile, social pages, packaging, QR codes and existing relationships. A marketplace may provide discovery or delivery services that you still need to replace. The calculator compares costs on the same sales volume; it does not promise more orders or unchanged demand."],
  ["Can I use this for a chip shop, pizzeria, café or restaurant?", "Yes. Adapt the menu, imagery, prices, opening hours and delivery or collection information to suit your business. Replace every demo detail, check allergens and test how orders reach your team before launch."],
];
const euro = (value: number) => new Intl.NumberFormat("en-IE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value);

function SavingsCalculator() {
  const [sales, setSales] = useState(10000);
  const [commission, setCommission] = useState(14);
  const [other, setOther] = useState(0);
  const [direct, setDirect] = useState(100);
  const current = sales * commission / 100 + other;
  const saving = current - direct;
  return <section className="takeaway-calculator" id="savings" aria-labelledby="savings-title">
    <div><span className="takeaway-kicker">PUT YOUR OWN NUMBERS IN</span><h2 id="savings-title">What could stay<br />in your business?</h2><p>Compare the cost of serving the same monthly sales through your own website. Use your invoices for a useful comparison.</p>
      <div className="takeaway-fields">
        <label>Monthly sales you would move (€)<input type="number" min="0" max="10000000" step="100" value={sales} onChange={e => setSales(Math.min(10000000, Math.max(0, Number(e.target.value) || 0)))} /></label>
        <label>Current platform commission (%)<input type="number" min="0" max="100" step="0.1" value={commission} onChange={e => setCommission(Math.min(100, Math.max(0, Number(e.target.value) || 0)))} /></label>
        <label>Other current monthly costs (€)<input type="number" min="0" max="1000000" value={other} onChange={e => setOther(Math.min(1000000, Math.max(0, Number(e.target.value) || 0)))} /><small>Add processing and fixed fees not already included in your commission.</small></label>
        <label>All direct website monthly costs (€)<input type="number" min="0" max="1000000" value={direct} onChange={e => setDirect(Math.min(1000000, Math.max(0, Number(e.target.value) || 0)))} /><small>Include your plan in euros, domain, payment processing, usage, marketing and any replacement delivery or support costs.</small></label>
      </div>
    </div>
    <div className="takeaway-receipt" aria-live="polite" aria-atomic="true"><UtensilsCrossed size={26} /><span>YOUR POSSIBLE NEXT CHAPTER</span><h3>{saving >= 0 ? "More of the good stuff." : "Check the numbers."}</h3><dl><div><dt>Current monthly costs</dt><dd>{euro(current)}</dd></div><div><dt>Your direct website costs</dt><dd>{euro(direct)}</dd></div><div><dt>KAMROK commission</dt><dd>0%</dd></div></dl><p className="takeaway-saving">{euro(Math.abs(saving))}<small>{saving >= 0 ? "illustrative monthly saving" : "additional monthly cost in this example"}</small></p><p className="takeaway-annual">{euro(Math.abs(saving) * 12)} {saving >= 0 ? "potentially saved" : "additional cost"} over 12 months</p><p className="takeaway-calculator-note">Example inputs, not a quote or a forecast. Assumes the same sales each month. Include all costs and VAT consistently. The €100 default is a placeholder for your total costs, not a Lovable plan price.</p></div>
  </section>;
}
export default function TakeawayHub() {
  useEffect(() => {
    const script = document.createElement("script");
    script.type = "application/ld+json";
    script.textContent = JSON.stringify({ "@context": "https://schema.org", "@graph": [
      { "@type": "WebPage", "@id": "https://kamrok.com/templates/takeaway-hub", url: "https://kamrok.com/templates/takeaway-hub", name: "Commission-Free Takeaway Website Template | KAMROK", description: "Launch your own takeaway website with a free DIY Lovable template and 0% KAMROK order commission." },
      { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Templates", item: "https://kamrok.com/templates" }, { "@type": "ListItem", position: 2, name: "Takeaway Hub", item: "https://kamrok.com/templates/takeaway-hub" }] },
      { "@type": "FAQPage", mainEntity: FAQ.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
    ] });
    document.head.appendChild(script);
    return () => script.remove();
  }, []);
  return <KamrokLayout title="Commission-Free Takeaway Website Template | KAMROK" description="Launch your own takeaway website with Takeaway Hub. Free DIY Lovable template, no KAMROK design fee and 0% order commission. Explore the demo and calculate savings.">
    <div className="takeaway-page">
      <nav className="takeaway-breadcrumb" aria-label="Breadcrumb"><Link to="/templates">Templates</Link><span>/</span><span>Takeaway Hub</span></nav>
      <section className="takeaway-hero">
        <div className="takeaway-hero-copy"><span className="takeaway-kicker"><Store size={15} /> YOUR INDEPENDENT TAKEAWAY WEBSITE</span><h1>Your menu.<br />Your website.<br /><em>Your slice.</em></h1><p>Launch your own takeaway website. Keep your brand front and centre, your customers close and more of every order in your business.</p><div className="takeaway-promises"><span><Check size={16} /> No DIY website design fees</span><span><Check size={16} /> 0% KAMROK order commission</span></div><div className="takeaway-actions"><a className="takeaway-primary" href={LOVABLE_AFFILIATE_URL} target="_blank" rel="sponsored noopener noreferrer">Start your takeaway hub <ArrowUpRight size={20} /></a><a className="takeaway-secondary" href={DEMO} target="_blank" rel="noopener noreferrer">Explore the live demo <ArrowUpRight size={18} /></a></div><p className="takeaway-fine">Free template. Your own Lovable account. Plan, domain, payment processing and any additional usage or services are paid separately. Start button uses my affiliate link.</p><a className="takeaway-savings-link" href="#savings">Work out your savings <ArrowDown size={16} /></a></div>
        <div className="takeaway-hero-visual"><div className="takeaway-zero"><strong>0<span>%</span></strong><span>OUR CUT OF YOUR ORDERS.</span></div><a href={DEMO} target="_blank" rel="noopener noreferrer" className="takeaway-browser"><div><i /><i /><i /><span>YOUR BRAND. YOUR OWN ADDRESS.</span><ArrowUpRight size={16} /></div><img src="/templates/takeaway-hub/website.webp" alt="Takeaway Hub website template showing a food menu, opening hours and an ordering journey" width="1219" height="894" /></a><div className="takeaway-stamp">Made by KAMROK.<br /><strong>Made yours with Lovable.</strong></div></div>
      </section>
      <div className="takeaway-strip"><span>YOUR NAME ABOVE THE DOOR</span><Plus /><span>YOUR MENU ON THE SCREEN</span><Plus /><span>YOUR BUSINESS IN CONTROL</span></div>
      <section className="takeaway-section takeaway-ownership"><div><span className="takeaway-kicker">A DIRECT ROUTE TO YOUR CUSTOMERS</span><h2>Great food deserves<br />its own front door.</h2></div><div><p className="takeaway-lead">Give your regulars somewhere that feels like you.</p><p>Takeaway Hub is a ready-designed starting point for independent takeaways, chip shops, pizzerias, cafés and restaurants. Change the name, add your dishes and build a direct ordering experience around the way you work.</p><p>You manage the project in your own Lovable account. KAMROK doesn’t take a percentage when someone orders dinner. Start with the template, then add the features your business needs.</p></div></section>
      <TakeawayShowcase />
      <section className="takeaway-section-heading takeaway-included" aria-labelledby="included-title"><span className="takeaway-kicker">THE TOOLS TO RUN YOUR OWN TAKEAWAY</span><h2 id="included-title">From the first topping<br />to the front door.</h2><p>A customer ordering experience and owner controls, with a practical remix guide to make the menu, rewards and delivery workflow yours.</p></section>
      <section className="takeaway-feature-grid" aria-label="Included takeaway features">{[
        ["01", "Pizza, your way", "Let customers choose their pizza options. Owners edit the choices, while the backend checks pizza and combo prices before an order is accepted."],
        ["02", "Deals on your schedule", "Create combo deals and schedule when they run. Keep your offers in step with busy nights, quieter hours and your next promotion."],
        ["03", "Rewards that add up", "Set your own rewards. Points cannot be awarded twice for the same order, and cancelling an order returns any points the customer redeemed."],
        ["04", "Your kitchen, in control", "Manage time estimates from the owner controls and give customers a clearer kitchen-to-delivery timeline as their order progresses."],
        ["05", "A link for each driver", "Create individual driver links from delivery orders. Live sharing lets customers follow a current position; stale locations are hidden automatically."],
        ["06", "Customer & owner spaces", "Customer screens and owner controls give each side the tools they need, with layouts designed for smaller screens as well as desktop."],
        ["07", "Your brand on the menu", "Make the photography, dishes, prices, opening hours and delivery information your own. Connect your domain and your payment account."],
        ["08", "A guide to making it yours", "Follow the practical remix guide to configure your menu, rewards and delivery workflow. Run a complete test order before opening for business."],
      ].map(([n,t,p]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</section>
      <p className="takeaway-tracking-note">Live driver sharing needs HTTPS, location permission and an open browser tab on the driver’s device. Positions disappear when they become stale.</p>
      <section className="takeaway-section takeaway-comparison" id="compare" aria-labelledby="compare-title">
        <div className="takeaway-section-heading"><span className="takeaway-kicker">MORE INDEPENDENCE. LESS UPFRONT SPEND.</span><h2 id="compare-title">Before you pay for a build,<br />see what you can make.</h2><p>Studios and freelancers also build on Wix — Wix has its own marketplace of professionals. Their fee pays for the work they do, separately from the platform subscription. If you are happy to customise a starter yourself, you can skip that design and setup bill.</p></div>
        <div className="takeaway-quote-examples"><article><span>IF YOUR STUDIO SETUP QUOTE IS</span><strong>€500</strong><p>Use the €0 DIY template and avoid a <b>€500 upfront setup fee.</b></p></article><article><span>IF YOUR STUDIO SETUP QUOTE IS</span><strong>€2,000</strong><p>Use the €0 DIY template and avoid a <b>€2,000 upfront setup fee.</b></p></article><article><span>YOUR KAMROK DIY STARTING POINT</span><strong>€0</strong><p>No template design or build charge. <b>You customise. You launch. You take control.</b></p></article></div>
        <p className="takeaway-fine">Illustrative quotes, not an industry average or claims about a particular studio. DIY takes your time; a professional quote may include bespoke design, content, integrations and support. Platform, domain and running costs still apply.</p>
        <div className="takeaway-table-wrap" role="region" aria-label="Takeaway website cost comparison" tabIndex={0}><table><caption>Compare the cost of the build and the cost of running it separately.</caption><thead><tr><th scope="col">What you pay for</th><th scope="col">Takeaway Hub · DIY on Lovable</th><th scope="col">Wix · DIY</th><th scope="col">Wix · built by a studio</th></tr></thead><tbody>
          <tr><th scope="row">Design & setup</th><td>€0 KAMROK template fee</td><td>No hired designer required if you build it yourself</td><td>The studio’s quoted project fee</td></tr>
          <tr><th scope="row">Platform & hosting</th><td>Lovable Pro from US$25/month; extra usage may apply</td><td>Paid plan for payments; Core or above. Check your local price and billing term.</td><td>Wix plan, plus any agreed studio maintenance</td></tr>
          <tr><th scope="row">Order commission</th><td>0% KAMROK commission</td><td>Wix Restaurants offers commission-free orders</td><td>Wix Restaurants is commission-free; check the studio’s contract for extra services</td></tr>
          <tr><th scope="row">Other costs</th><td>Domain, payment provider and any extra services</td><td>Domain renewal, payment processing and paid extras</td><td>The same platform costs, plus services in your agreement</td></tr>
          <tr><th scope="row">Making changes</th><td>You adapt your project in your own Lovable workspace</td><td>You edit your site with Wix tools</td><td>Agree your access, handover and ongoing support with the studio</td></tr>
        </tbody></table></div>
        <p className="takeaway-fine">Wix prices vary by location and billing period; its advertised monthly equivalent can require annual payment upfront. Compare your actual checkout totals. Sources: <a href="https://www.wix.com/plans" target="_blank" rel="noopener noreferrer">Wix plans</a>, <a href="https://www.wix.com/restaurant/website" target="_blank" rel="noopener noreferrer">Wix Restaurants</a>, <a href="https://www.wix.com/marketplace" target="_blank" rel="noopener noreferrer">Wix professionals</a> and <a href="https://lovable.dev/pricing" target="_blank" rel="noopener noreferrer">Lovable pricing</a>. Checked October 2026.</p>
        <p className="takeaway-independence">The internet revolution should work for your business. Start with the tools. Make them yours. Keep building.</p>
      </section>
      <SavingsCalculator />
      <section className="takeaway-section" id="costs"><div className="takeaway-section-heading"><span className="takeaway-kicker">NO HIDDEN KAMROK FEES. HERE’S THE WHOLE PICTURE.</span><h2>Free to make yours.<br />Clear about the costs.</h2><p>No catch in the small print: we give you the DIY starting point. You pay the providers you choose to run it.</p></div><div className="takeaway-costs">
        <article><span>THE KAMROK TEMPLATE</span><strong>€0</strong><h3>No website design bill.</h3><p>No KAMROK template fee, DIY setup fee or order commission. Your time and your Lovable account do the customising.</p><small>Optional work you ask KAMROK to do is quoted separately.</small></article>
        <article><span>YOUR LOVABLE PLAN</span><strong>US$25<small>/mo from</small></strong><h3>Your own domain. Your own project.</h3><p>Pro is the starting plan for connecting your own domain. Pay Lovable directly and choose the capacity you need.</p><small>Domain registration, extra usage and taxes may be additional. Local price confirmed at checkout; checked October 2026.</small></article>
        <article><span>YOUR PAYMENT PROVIDER</span><CreditCard size={44} /><h3>Your account. Their processing rate.</h3><p>Connect your own Stripe account. Prefer another gateway? Check its API or hosted-checkout support before choosing the integration.</p><small>Provider processing, refunds, disputes and other account charges follow that provider’s terms.</small></article>
      </div></section>
      <section className="takeaway-section takeaway-connect"><div><span className="takeaway-kicker">YOUR TOOLS. WORKING TOGETHER.</span><h2>More than a menu.<br />As much as you make it.</h2><p>Build on the tools you already use. Lovable’s connectors give you ways to add useful features after you connect and configure your accounts.</p><p className="takeaway-fine">These are optional integrations to build, not features already connected to the demo. Provider permissions, approvals and usage charges may apply.</p></div><div className="takeaway-connections"><article><MessageCircle /><div><h3>WhatsApp Business</h3><p>Add customer messages and approved templates to your workflow.</p></div></article><article><Mail /><div><h3>Gmail</h3><p>Create email follow-ups and customer conversations from your connected inbox.</p></div></article><article><CreditCard /><div><h3>Stripe</h3><p>Build checkout with a payment account you own, then test before accepting live orders.</p></div></article><article><Plus /><div><h3>And your next good idea</h3><p>Explore Google Sheets, Maps and other connectors for the tools you want to add.</p></div></article></div></section>
      <section className="takeaway-section"><div className="takeaway-section-heading"><span className="takeaway-kicker">FROM A STARTING POINT TO YOUR FRONT DOOR</span><h2>Make it yours. Get it live.</h2></div><ol className="takeaway-steps"><li><span>01</span><h3>Explore the demo</h3><p>Try the menu and see how the design could work for your takeaway.</p></li><li><span>02</span><h3>Start your own version</h3><p>Create your own Lovable account and workspace. Get the template, then replace the example branding, menu, prices and business details.</p></li><li><span>03</span><h3>Connect & check</h3><p>Set up your domain, payments and order workflow. Check allergens, delivery rules and a complete test order.</p></li><li><span>04</span><h3>Open your digital doors</h3><p>Publish when ready. Share your link on Google, social pages, packaging and QR codes to bring customers directly to you.</p></li></ol></section>
      <section className="takeaway-section takeaway-faq"><div><span className="takeaway-kicker">GOOD QUESTIONS. STRAIGHT ANSWERS.</span><h2>Before the<br />first order.</h2><p>Considering an alternative to Munchd or another ordering platform? Compare the full running costs and the services you need, including delivery, customer acquisition and support.</p></div><div>{FAQ.map(([q,a]) => <details key={q}><summary>{q}<Plus size={18} /></summary><p>{a}</p></details>)}</div></section>
      <section className="takeaway-close"><span className="takeaway-kicker">YOUR NEXT ORDER COULD START HERE</span><h2>Keep the flavour.<br />Keep your independence.</h2><p>Your own takeaway website. A free DIY starting point. Zero KAMROK commission.</p><div className="takeaway-actions"><a className="takeaway-primary" href={DEMO} target="_blank" rel="noopener noreferrer">Explore the live demo <ArrowUpRight /></a><a className="takeaway-secondary" href={LOVABLE_AFFILIATE_URL} target="_blank" rel="sponsored noopener noreferrer">Start your takeaway hub <ArrowUpRight /></a></div><p className="takeaway-fine">Already ready to build? <a href={LOVABLE_AFFILIATE_URL} target="_blank" rel="sponsored noopener noreferrer">Create your Lovable account</a> using my affiliate link. <Link to="/contact?service=Free%20Takeaway%20Hub%20template">Need help accessing the template?</Link> Prefer to talk? <a href={CONTACT_TEL}>{CONTACT_PHONE}</a>.</p></section>
      <aside className="takeaway-sources">Plan and connector details checked against <a href="https://lovable.dev/pricing" target="_blank" rel="noopener noreferrer">Lovable pricing</a>, <a href="https://lovable.dev/connect" target="_blank" rel="noopener noreferrer">its connector catalogue</a> and <a href="https://docs.lovable.dev/integrations/stripe" target="_blank" rel="noopener noreferrer">the Stripe setup guide</a>. October 2026.</aside>
    </div>
  </KamrokLayout>;
}
