/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/_studio'
import { Route as FunRouteImport } from './routes/fun'
import { Route as StudioIndexRouteImport } from './routes/_studio/index'
import { Route as StudioSplatRouteImport } from './routes/_studio/$'
import { Route as StudioAboutRouteImport } from './routes/_studio/about'
import { Route as StudioContactRouteImport } from './routes/_studio/contact'
import { Route as StudioIllustrationsRouteImport } from './routes/_studio/illustrations'
import { Route as StudioLovableSavingsRouteImport } from './routes/_studio/lovable-savings'
import { Route as StudioProjectPlannerRouteImport } from './routes/_studio/project-planner'
import { Route as StudioSkillsRouteImport } from './routes/_studio/skills'
import { Route as ApiSitemapAuditRouteImport } from './routes/api/sitemap-audit'
import { Route as StudioBlogIndexRouteImport } from './routes/_studio/blog/index'
import { Route as StudioBlogDundalkSeoGuideRouteImport } from './routes/_studio/blog/dundalk-seo-guide'
import { Route as StudioServicesServiceRouteImport } from './routes/_studio/services/$service'
import { Route as StudioTemplatesIndexRouteImport } from './routes/_studio/templates/index'
import { Route as StudioTemplatesTakeawayHubRouteImport } from './routes/_studio/templates/takeaway-hub'
import { Route as StudioToolsIndexRouteImport } from './routes/_studio/tools/index'
import { Route as StudioToolsBookingsDemosRouteImport } from './routes/_studio/tools/bookings-demos'
import { Route as StudioToolsBusinessNameGeneratorRouteImport } from './routes/_studio/tools/business-name-generator'
import { Route as StudioToolsChatLeadCaptureRouteImport } from './routes/_studio/tools/chat-lead-capture'
import { Route as StudioToolsCookieConsentManagerRouteImport } from './routes/_studio/tools/cookie-consent-manager'
import { Route as StudioToolsEmailSignatureRouteImport } from './routes/_studio/tools/email-signature'
import { Route as StudioToolsHashtagSuggesterRouteImport } from './routes/_studio/tools/hashtag-suggester'
import { Route as StudioToolsInvoiceCreatorRouteImport } from './routes/_studio/tools/invoice-creator'
import { Route as StudioToolsOpengraphPreviewRouteImport } from './routes/_studio/tools/opengraph-preview'
import { Route as StudioToolsPasswordGeneratorRouteImport } from './routes/_studio/tools/password-generator'
import { Route as StudioToolsPopupOfferEngineRouteImport } from './routes/_studio/tools/popup-offer-engine'
import { Route as StudioToolsPrivacyPolicyBuilderRouteImport } from './routes/_studio/tools/privacy-policy-builder'
import { Route as StudioToolsQrCodeGeneratorRouteImport } from './routes/_studio/tools/qr-code-generator'
import { Route as StudioToolsQuotationMakerRouteImport } from './routes/_studio/tools/quotation-maker'
import { Route as StudioToolsReviewWidgetRouteImport } from './routes/_studio/tools/review-widget'
import { Route as StudioToolsSocialPostSizesRouteImport } from './routes/_studio/tools/social-post-sizes'
import { Route as StudioToolsSocialWallRouteImport } from './routes/_studio/tools/social-wall'
import { Route as StudioToolsTermsGeneratorRouteImport } from './routes/_studio/tools/terms-generator'
import { Route as StudioToolsTrustpilotIntegrationRouteImport } from './routes/_studio/tools/trustpilot-integration'
import { Route as StudioToolsUtmBuilderRouteImport } from './routes/_studio/tools/utm-builder'
import { Route as StudioToolsVatCalculatorRouteImport } from './routes/_studio/tools/vat-calculator'
import { Route as StudioWorkIndexRouteImport } from './routes/_studio/work/index'
import { Route as StudioWorkSlugRouteImport } from './routes/_studio/work/$slug'

const StudioRoute = StudioRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const FunRoute = FunRouteImport.update({
  id: '/fun',
  path: '/fun',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSplatRoute = StudioSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAboutRoute = StudioAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => StudioRoute,
} as any)
const StudioContactRoute = StudioContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => StudioRoute,
} as any)
const StudioIllustrationsRoute = StudioIllustrationsRouteImport.update({
  id: '/illustrations',
  path: '/illustrations',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLovableSavingsRoute = StudioLovableSavingsRouteImport.update({
  id: '/lovable-savings',
  path: '/lovable-savings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioProjectPlannerRoute = StudioProjectPlannerRouteImport.update({
  id: '/project-planner',
  path: '/project-planner',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSkillsRoute = StudioSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => StudioRoute,
} as any)
const ApiSitemapAuditRoute = ApiSitemapAuditRouteImport.update({
  id: '/api/sitemap-audit',
  path: '/api/sitemap-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioBlogIndexRoute = StudioBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBlogDundalkSeoGuideRoute =
  StudioBlogDundalkSeoGuideRouteImport.update({
    id: '/blog/dundalk-seo-guide',
    path: '/blog/dundalk-seo-guide',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioServicesServiceRoute = StudioServicesServiceRouteImport.update({
  id: '/services/$service',
  path: '/services/$service',
  getParentRoute: () => StudioRoute,
} as any)
const StudioTemplatesIndexRoute = StudioTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioTemplatesTakeawayHubRoute =
  StudioTemplatesTakeawayHubRouteImport.update({
    id: '/templates/takeaway-hub',
    path: '/templates/takeaway-hub',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsIndexRoute = StudioToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioToolsBookingsDemosRoute =
  StudioToolsBookingsDemosRouteImport.update({
    id: '/tools/bookings-demos',
    path: '/tools/bookings-demos',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsBusinessNameGeneratorRoute =
  StudioToolsBusinessNameGeneratorRouteImport.update({
    id: '/tools/business-name-generator',
    path: '/tools/business-name-generator',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsChatLeadCaptureRoute =
  StudioToolsChatLeadCaptureRouteImport.update({
    id: '/tools/chat-lead-capture',
    path: '/tools/chat-lead-capture',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsCookieConsentManagerRoute =
  StudioToolsCookieConsentManagerRouteImport.update({
    id: '/tools/cookie-consent-manager',
    path: '/tools/cookie-consent-manager',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsEmailSignatureRoute =
  StudioToolsEmailSignatureRouteImport.update({
    id: '/tools/email-signature',
    path: '/tools/email-signature',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsHashtagSuggesterRoute =
  StudioToolsHashtagSuggesterRouteImport.update({
    id: '/tools/hashtag-suggester',
    path: '/tools/hashtag-suggester',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsInvoiceCreatorRoute =
  StudioToolsInvoiceCreatorRouteImport.update({
    id: '/tools/invoice-creator',
    path: '/tools/invoice-creator',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsOpengraphPreviewRoute =
  StudioToolsOpengraphPreviewRouteImport.update({
    id: '/tools/opengraph-preview',
    path: '/tools/opengraph-preview',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsPasswordGeneratorRoute =
  StudioToolsPasswordGeneratorRouteImport.update({
    id: '/tools/password-generator',
    path: '/tools/password-generator',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsPopupOfferEngineRoute =
  StudioToolsPopupOfferEngineRouteImport.update({
    id: '/tools/popup-offer-engine',
    path: '/tools/popup-offer-engine',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsPrivacyPolicyBuilderRoute =
  StudioToolsPrivacyPolicyBuilderRouteImport.update({
    id: '/tools/privacy-policy-builder',
    path: '/tools/privacy-policy-builder',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsQrCodeGeneratorRoute =
  StudioToolsQrCodeGeneratorRouteImport.update({
    id: '/tools/qr-code-generator',
    path: '/tools/qr-code-generator',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsQuotationMakerRoute =
  StudioToolsQuotationMakerRouteImport.update({
    id: '/tools/quotation-maker',
    path: '/tools/quotation-maker',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsReviewWidgetRoute = StudioToolsReviewWidgetRouteImport.update({
  id: '/tools/review-widget',
  path: '/tools/review-widget',
  getParentRoute: () => StudioRoute,
} as any)
const StudioToolsSocialPostSizesRoute =
  StudioToolsSocialPostSizesRouteImport.update({
    id: '/tools/social-post-sizes',
    path: '/tools/social-post-sizes',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsSocialWallRoute = StudioToolsSocialWallRouteImport.update({
  id: '/tools/social-wall',
  path: '/tools/social-wall',
  getParentRoute: () => StudioRoute,
} as any)
const StudioToolsTermsGeneratorRoute =
  StudioToolsTermsGeneratorRouteImport.update({
    id: '/tools/terms-generator',
    path: '/tools/terms-generator',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsTrustpilotIntegrationRoute =
  StudioToolsTrustpilotIntegrationRouteImport.update({
    id: '/tools/trustpilot-integration',
    path: '/tools/trustpilot-integration',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioToolsUtmBuilderRoute = StudioToolsUtmBuilderRouteImport.update({
  id: '/tools/utm-builder',
  path: '/tools/utm-builder',
  getParentRoute: () => StudioRoute,
} as any)
const StudioToolsVatCalculatorRoute =
  StudioToolsVatCalculatorRouteImport.update({
    id: '/tools/vat-calculator',
    path: '/tools/vat-calculator',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioWorkIndexRoute = StudioWorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioWorkSlugRoute = StudioWorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StudioIndexRoute
  '/fun': typeof FunRoute
  '/$': typeof StudioSplatRoute
  '/about': typeof StudioAboutRoute
  '/contact': typeof StudioContactRoute
  '/illustrations': typeof StudioIllustrationsRoute
  '/lovable-savings': typeof StudioLovableSavingsRoute
  '/project-planner': typeof StudioProjectPlannerRoute
  '/skills': typeof StudioSkillsRoute
  '/api/sitemap-audit': typeof ApiSitemapAuditRoute
  '/blog/dundalk-seo-guide': typeof StudioBlogDundalkSeoGuideRoute
  '/services/$service': typeof StudioServicesServiceRoute
  '/templates/takeaway-hub': typeof StudioTemplatesTakeawayHubRoute
  '/tools/bookings-demos': typeof StudioToolsBookingsDemosRoute
  '/tools/business-name-generator': typeof StudioToolsBusinessNameGeneratorRoute
  '/tools/chat-lead-capture': typeof StudioToolsChatLeadCaptureRoute
  '/tools/cookie-consent-manager': typeof StudioToolsCookieConsentManagerRoute
  '/tools/email-signature': typeof StudioToolsEmailSignatureRoute
  '/tools/hashtag-suggester': typeof StudioToolsHashtagSuggesterRoute
  '/tools/invoice-creator': typeof StudioToolsInvoiceCreatorRoute
  '/tools/opengraph-preview': typeof StudioToolsOpengraphPreviewRoute
  '/tools/password-generator': typeof StudioToolsPasswordGeneratorRoute
  '/tools/popup-offer-engine': typeof StudioToolsPopupOfferEngineRoute
  '/tools/privacy-policy-builder': typeof StudioToolsPrivacyPolicyBuilderRoute
  '/tools/qr-code-generator': typeof StudioToolsQrCodeGeneratorRoute
  '/tools/quotation-maker': typeof StudioToolsQuotationMakerRoute
  '/tools/review-widget': typeof StudioToolsReviewWidgetRoute
  '/tools/social-post-sizes': typeof StudioToolsSocialPostSizesRoute
  '/tools/social-wall': typeof StudioToolsSocialWallRoute
  '/tools/terms-generator': typeof StudioToolsTermsGeneratorRoute
  '/tools/trustpilot-integration': typeof StudioToolsTrustpilotIntegrationRoute
  '/tools/utm-builder': typeof StudioToolsUtmBuilderRoute
  '/tools/vat-calculator': typeof StudioToolsVatCalculatorRoute
  '/work/$slug': typeof StudioWorkSlugRoute
  '/blog/': typeof StudioBlogIndexRoute
  '/templates/': typeof StudioTemplatesIndexRoute
  '/tools/': typeof StudioToolsIndexRoute
  '/work/': typeof StudioWorkIndexRoute
}
export interface FileRoutesByTo {
  '/fun': typeof FunRoute
  '/$': typeof StudioSplatRoute
  '/about': typeof StudioAboutRoute
  '/contact': typeof StudioContactRoute
  '/illustrations': typeof StudioIllustrationsRoute
  '/lovable-savings': typeof StudioLovableSavingsRoute
  '/project-planner': typeof StudioProjectPlannerRoute
  '/skills': typeof StudioSkillsRoute
  '/api/sitemap-audit': typeof ApiSitemapAuditRoute
  '/': typeof StudioIndexRoute
  '/blog/dundalk-seo-guide': typeof StudioBlogDundalkSeoGuideRoute
  '/services/$service': typeof StudioServicesServiceRoute
  '/templates/takeaway-hub': typeof StudioTemplatesTakeawayHubRoute
  '/tools/bookings-demos': typeof StudioToolsBookingsDemosRoute
  '/tools/business-name-generator': typeof StudioToolsBusinessNameGeneratorRoute
  '/tools/chat-lead-capture': typeof StudioToolsChatLeadCaptureRoute
  '/tools/cookie-consent-manager': typeof StudioToolsCookieConsentManagerRoute
  '/tools/email-signature': typeof StudioToolsEmailSignatureRoute
  '/tools/hashtag-suggester': typeof StudioToolsHashtagSuggesterRoute
  '/tools/invoice-creator': typeof StudioToolsInvoiceCreatorRoute
  '/tools/opengraph-preview': typeof StudioToolsOpengraphPreviewRoute
  '/tools/password-generator': typeof StudioToolsPasswordGeneratorRoute
  '/tools/popup-offer-engine': typeof StudioToolsPopupOfferEngineRoute
  '/tools/privacy-policy-builder': typeof StudioToolsPrivacyPolicyBuilderRoute
  '/tools/qr-code-generator': typeof StudioToolsQrCodeGeneratorRoute
  '/tools/quotation-maker': typeof StudioToolsQuotationMakerRoute
  '/tools/review-widget': typeof StudioToolsReviewWidgetRoute
  '/tools/social-post-sizes': typeof StudioToolsSocialPostSizesRoute
  '/tools/social-wall': typeof StudioToolsSocialWallRoute
  '/tools/terms-generator': typeof StudioToolsTermsGeneratorRoute
  '/tools/trustpilot-integration': typeof StudioToolsTrustpilotIntegrationRoute
  '/tools/utm-builder': typeof StudioToolsUtmBuilderRoute
  '/tools/vat-calculator': typeof StudioToolsVatCalculatorRoute
  '/work/$slug': typeof StudioWorkSlugRoute
  '/blog': typeof StudioBlogIndexRoute
  '/templates': typeof StudioTemplatesIndexRoute
  '/tools': typeof StudioToolsIndexRoute
  '/work': typeof StudioWorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_studio': typeof StudioRouteWithChildren
  '/fun': typeof FunRoute
  '/_studio/$': typeof StudioSplatRoute
  '/_studio/about': typeof StudioAboutRoute
  '/_studio/contact': typeof StudioContactRoute
  '/_studio/illustrations': typeof StudioIllustrationsRoute
  '/_studio/lovable-savings': typeof StudioLovableSavingsRoute
  '/_studio/project-planner': typeof StudioProjectPlannerRoute
  '/_studio/skills': typeof StudioSkillsRoute
  '/api/sitemap-audit': typeof ApiSitemapAuditRoute
  '/_studio/': typeof StudioIndexRoute
  '/_studio/blog/dundalk-seo-guide': typeof StudioBlogDundalkSeoGuideRoute
  '/_studio/services/$service': typeof StudioServicesServiceRoute
  '/_studio/templates/takeaway-hub': typeof StudioTemplatesTakeawayHubRoute
  '/_studio/tools/bookings-demos': typeof StudioToolsBookingsDemosRoute
  '/_studio/tools/business-name-generator': typeof StudioToolsBusinessNameGeneratorRoute
  '/_studio/tools/chat-lead-capture': typeof StudioToolsChatLeadCaptureRoute
  '/_studio/tools/cookie-consent-manager': typeof StudioToolsCookieConsentManagerRoute
  '/_studio/tools/email-signature': typeof StudioToolsEmailSignatureRoute
  '/_studio/tools/hashtag-suggester': typeof StudioToolsHashtagSuggesterRoute
  '/_studio/tools/invoice-creator': typeof StudioToolsInvoiceCreatorRoute
  '/_studio/tools/opengraph-preview': typeof StudioToolsOpengraphPreviewRoute
  '/_studio/tools/password-generator': typeof StudioToolsPasswordGeneratorRoute
  '/_studio/tools/popup-offer-engine': typeof StudioToolsPopupOfferEngineRoute
  '/_studio/tools/privacy-policy-builder': typeof StudioToolsPrivacyPolicyBuilderRoute
  '/_studio/tools/qr-code-generator': typeof StudioToolsQrCodeGeneratorRoute
  '/_studio/tools/quotation-maker': typeof StudioToolsQuotationMakerRoute
  '/_studio/tools/review-widget': typeof StudioToolsReviewWidgetRoute
  '/_studio/tools/social-post-sizes': typeof StudioToolsSocialPostSizesRoute
  '/_studio/tools/social-wall': typeof StudioToolsSocialWallRoute
  '/_studio/tools/terms-generator': typeof StudioToolsTermsGeneratorRoute
  '/_studio/tools/trustpilot-integration': typeof StudioToolsTrustpilotIntegrationRoute
  '/_studio/tools/utm-builder': typeof StudioToolsUtmBuilderRoute
  '/_studio/tools/vat-calculator': typeof StudioToolsVatCalculatorRoute
  '/_studio/work/$slug': typeof StudioWorkSlugRoute
  '/_studio/blog/': typeof StudioBlogIndexRoute
  '/_studio/templates/': typeof StudioTemplatesIndexRoute
  '/_studio/tools/': typeof StudioToolsIndexRoute
  '/_studio/work/': typeof StudioWorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fun'
    | '/$'
    | '/about'
    | '/contact'
    | '/illustrations'
    | '/lovable-savings'
    | '/project-planner'
    | '/skills'
    | '/api/sitemap-audit'
    | '/blog/dundalk-seo-guide'
    | '/services/$service'
    | '/templates/takeaway-hub'
    | '/tools/bookings-demos'
    | '/tools/business-name-generator'
    | '/tools/chat-lead-capture'
    | '/tools/cookie-consent-manager'
    | '/tools/email-signature'
    | '/tools/hashtag-suggester'
    | '/tools/invoice-creator'
    | '/tools/opengraph-preview'
    | '/tools/password-generator'
    | '/tools/popup-offer-engine'
    | '/tools/privacy-policy-builder'
    | '/tools/qr-code-generator'
    | '/tools/quotation-maker'
    | '/tools/review-widget'
    | '/tools/social-post-sizes'
    | '/tools/social-wall'
    | '/tools/terms-generator'
    | '/tools/trustpilot-integration'
    | '/tools/utm-builder'
    | '/tools/vat-calculator'
    | '/work/$slug'
    | '/blog/'
    | '/templates/'
    | '/tools/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/fun'
    | '/$'
    | '/about'
    | '/contact'
    | '/illustrations'
    | '/lovable-savings'
    | '/project-planner'
    | '/skills'
    | '/api/sitemap-audit'
    | '/'
    | '/blog/dundalk-seo-guide'
    | '/services/$service'
    | '/templates/takeaway-hub'
    | '/tools/bookings-demos'
    | '/tools/business-name-generator'
    | '/tools/chat-lead-capture'
    | '/tools/cookie-consent-manager'
    | '/tools/email-signature'
    | '/tools/hashtag-suggester'
    | '/tools/invoice-creator'
    | '/tools/opengraph-preview'
    | '/tools/password-generator'
    | '/tools/popup-offer-engine'
    | '/tools/privacy-policy-builder'
    | '/tools/qr-code-generator'
    | '/tools/quotation-maker'
    | '/tools/review-widget'
    | '/tools/social-post-sizes'
    | '/tools/social-wall'
    | '/tools/terms-generator'
    | '/tools/trustpilot-integration'
    | '/tools/utm-builder'
    | '/tools/vat-calculator'
    | '/work/$slug'
    | '/blog'
    | '/templates'
    | '/tools'
    | '/work'
  id:
    | '__root__'
    | '/_studio'
    | '/fun'
    | '/_studio/$'
    | '/_studio/about'
    | '/_studio/contact'
    | '/_studio/illustrations'
    | '/_studio/lovable-savings'
    | '/_studio/project-planner'
    | '/_studio/skills'
    | '/api/sitemap-audit'
    | '/_studio/'
    | '/_studio/blog/dundalk-seo-guide'
    | '/_studio/services/$service'
    | '/_studio/templates/takeaway-hub'
    | '/_studio/tools/bookings-demos'
    | '/_studio/tools/business-name-generator'
    | '/_studio/tools/chat-lead-capture'
    | '/_studio/tools/cookie-consent-manager'
    | '/_studio/tools/email-signature'
    | '/_studio/tools/hashtag-suggester'
    | '/_studio/tools/invoice-creator'
    | '/_studio/tools/opengraph-preview'
    | '/_studio/tools/password-generator'
    | '/_studio/tools/popup-offer-engine'
    | '/_studio/tools/privacy-policy-builder'
    | '/_studio/tools/qr-code-generator'
    | '/_studio/tools/quotation-maker'
    | '/_studio/tools/review-widget'
    | '/_studio/tools/social-post-sizes'
    | '/_studio/tools/social-wall'
    | '/_studio/tools/terms-generator'
    | '/_studio/tools/trustpilot-integration'
    | '/_studio/tools/utm-builder'
    | '/_studio/tools/vat-calculator'
    | '/_studio/work/$slug'
    | '/_studio/blog/'
    | '/_studio/templates/'
    | '/_studio/tools/'
    | '/_studio/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StudioRoute: typeof StudioRouteWithChildren
  FunRoute: typeof FunRoute
  ApiSitemapAuditRoute: typeof ApiSitemapAuditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fun': {
      id: '/fun'
      path: '/fun'
      fullPath: '/fun'
      preLoaderRoute: typeof FunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/': {
      id: '/_studio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/$': {
      id: '/_studio/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof StudioSplatRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/about': {
      id: '/_studio/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof StudioAboutRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/contact': {
      id: '/_studio/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof StudioContactRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/illustrations': {
      id: '/_studio/illustrations'
      path: '/illustrations'
      fullPath: '/illustrations'
      preLoaderRoute: typeof StudioIllustrationsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/lovable-savings': {
      id: '/_studio/lovable-savings'
      path: '/lovable-savings'
      fullPath: '/lovable-savings'
      preLoaderRoute: typeof StudioLovableSavingsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/project-planner': {
      id: '/_studio/project-planner'
      path: '/project-planner'
      fullPath: '/project-planner'
      preLoaderRoute: typeof StudioProjectPlannerRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/skills': {
      id: '/_studio/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof StudioSkillsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/sitemap-audit': {
      id: '/api/sitemap-audit'
      path: '/api/sitemap-audit'
      fullPath: '/api/sitemap-audit'
      preLoaderRoute: typeof ApiSitemapAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/blog/': {
      id: '/_studio/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof StudioBlogIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/blog/dundalk-seo-guide': {
      id: '/_studio/blog/dundalk-seo-guide'
      path: '/blog/dundalk-seo-guide'
      fullPath: '/blog/dundalk-seo-guide'
      preLoaderRoute: typeof StudioBlogDundalkSeoGuideRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/services/$service': {
      id: '/_studio/services/$service'
      path: '/services/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof StudioServicesServiceRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/templates/': {
      id: '/_studio/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof StudioTemplatesIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/templates/takeaway-hub': {
      id: '/_studio/templates/takeaway-hub'
      path: '/templates/takeaway-hub'
      fullPath: '/templates/takeaway-hub'
      preLoaderRoute: typeof StudioTemplatesTakeawayHubRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/': {
      id: '/_studio/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof StudioToolsIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/bookings-demos': {
      id: '/_studio/tools/bookings-demos'
      path: '/tools/bookings-demos'
      fullPath: '/tools/bookings-demos'
      preLoaderRoute: typeof StudioToolsBookingsDemosRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/business-name-generator': {
      id: '/_studio/tools/business-name-generator'
      path: '/tools/business-name-generator'
      fullPath: '/tools/business-name-generator'
      preLoaderRoute: typeof StudioToolsBusinessNameGeneratorRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/chat-lead-capture': {
      id: '/_studio/tools/chat-lead-capture'
      path: '/tools/chat-lead-capture'
      fullPath: '/tools/chat-lead-capture'
      preLoaderRoute: typeof StudioToolsChatLeadCaptureRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/cookie-consent-manager': {
      id: '/_studio/tools/cookie-consent-manager'
      path: '/tools/cookie-consent-manager'
      fullPath: '/tools/cookie-consent-manager'
      preLoaderRoute: typeof StudioToolsCookieConsentManagerRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/email-signature': {
      id: '/_studio/tools/email-signature'
      path: '/tools/email-signature'
      fullPath: '/tools/email-signature'
      preLoaderRoute: typeof StudioToolsEmailSignatureRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/hashtag-suggester': {
      id: '/_studio/tools/hashtag-suggester'
      path: '/tools/hashtag-suggester'
      fullPath: '/tools/hashtag-suggester'
      preLoaderRoute: typeof StudioToolsHashtagSuggesterRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/invoice-creator': {
      id: '/_studio/tools/invoice-creator'
      path: '/tools/invoice-creator'
      fullPath: '/tools/invoice-creator'
      preLoaderRoute: typeof StudioToolsInvoiceCreatorRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/opengraph-preview': {
      id: '/_studio/tools/opengraph-preview'
      path: '/tools/opengraph-preview'
      fullPath: '/tools/opengraph-preview'
      preLoaderRoute: typeof StudioToolsOpengraphPreviewRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/password-generator': {
      id: '/_studio/tools/password-generator'
      path: '/tools/password-generator'
      fullPath: '/tools/password-generator'
      preLoaderRoute: typeof StudioToolsPasswordGeneratorRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/popup-offer-engine': {
      id: '/_studio/tools/popup-offer-engine'
      path: '/tools/popup-offer-engine'
      fullPath: '/tools/popup-offer-engine'
      preLoaderRoute: typeof StudioToolsPopupOfferEngineRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/privacy-policy-builder': {
      id: '/_studio/tools/privacy-policy-builder'
      path: '/tools/privacy-policy-builder'
      fullPath: '/tools/privacy-policy-builder'
      preLoaderRoute: typeof StudioToolsPrivacyPolicyBuilderRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/qr-code-generator': {
      id: '/_studio/tools/qr-code-generator'
      path: '/tools/qr-code-generator'
      fullPath: '/tools/qr-code-generator'
      preLoaderRoute: typeof StudioToolsQrCodeGeneratorRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/quotation-maker': {
      id: '/_studio/tools/quotation-maker'
      path: '/tools/quotation-maker'
      fullPath: '/tools/quotation-maker'
      preLoaderRoute: typeof StudioToolsQuotationMakerRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/review-widget': {
      id: '/_studio/tools/review-widget'
      path: '/tools/review-widget'
      fullPath: '/tools/review-widget'
      preLoaderRoute: typeof StudioToolsReviewWidgetRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/social-post-sizes': {
      id: '/_studio/tools/social-post-sizes'
      path: '/tools/social-post-sizes'
      fullPath: '/tools/social-post-sizes'
      preLoaderRoute: typeof StudioToolsSocialPostSizesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/social-wall': {
      id: '/_studio/tools/social-wall'
      path: '/tools/social-wall'
      fullPath: '/tools/social-wall'
      preLoaderRoute: typeof StudioToolsSocialWallRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/terms-generator': {
      id: '/_studio/tools/terms-generator'
      path: '/tools/terms-generator'
      fullPath: '/tools/terms-generator'
      preLoaderRoute: typeof StudioToolsTermsGeneratorRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/trustpilot-integration': {
      id: '/_studio/tools/trustpilot-integration'
      path: '/tools/trustpilot-integration'
      fullPath: '/tools/trustpilot-integration'
      preLoaderRoute: typeof StudioToolsTrustpilotIntegrationRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/utm-builder': {
      id: '/_studio/tools/utm-builder'
      path: '/tools/utm-builder'
      fullPath: '/tools/utm-builder'
      preLoaderRoute: typeof StudioToolsUtmBuilderRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/tools/vat-calculator': {
      id: '/_studio/tools/vat-calculator'
      path: '/tools/vat-calculator'
      fullPath: '/tools/vat-calculator'
      preLoaderRoute: typeof StudioToolsVatCalculatorRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/work/': {
      id: '/_studio/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof StudioWorkIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/work/$slug': {
      id: '/_studio/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof StudioWorkSlugRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface StudioRouteChildren {
  StudioSplatRoute: typeof StudioSplatRoute
  StudioAboutRoute: typeof StudioAboutRoute
  StudioContactRoute: typeof StudioContactRoute
  StudioIllustrationsRoute: typeof StudioIllustrationsRoute
  StudioLovableSavingsRoute: typeof StudioLovableSavingsRoute
  StudioProjectPlannerRoute: typeof StudioProjectPlannerRoute
  StudioSkillsRoute: typeof StudioSkillsRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioBlogDundalkSeoGuideRoute: typeof StudioBlogDundalkSeoGuideRoute
  StudioServicesServiceRoute: typeof StudioServicesServiceRoute
  StudioTemplatesTakeawayHubRoute: typeof StudioTemplatesTakeawayHubRoute
  StudioToolsBookingsDemosRoute: typeof StudioToolsBookingsDemosRoute
  StudioToolsBusinessNameGeneratorRoute: typeof StudioToolsBusinessNameGeneratorRoute
  StudioToolsChatLeadCaptureRoute: typeof StudioToolsChatLeadCaptureRoute
  StudioToolsCookieConsentManagerRoute: typeof StudioToolsCookieConsentManagerRoute
  StudioToolsEmailSignatureRoute: typeof StudioToolsEmailSignatureRoute
  StudioToolsHashtagSuggesterRoute: typeof StudioToolsHashtagSuggesterRoute
  StudioToolsInvoiceCreatorRoute: typeof StudioToolsInvoiceCreatorRoute
  StudioToolsOpengraphPreviewRoute: typeof StudioToolsOpengraphPreviewRoute
  StudioToolsPasswordGeneratorRoute: typeof StudioToolsPasswordGeneratorRoute
  StudioToolsPopupOfferEngineRoute: typeof StudioToolsPopupOfferEngineRoute
  StudioToolsPrivacyPolicyBuilderRoute: typeof StudioToolsPrivacyPolicyBuilderRoute
  StudioToolsQrCodeGeneratorRoute: typeof StudioToolsQrCodeGeneratorRoute
  StudioToolsQuotationMakerRoute: typeof StudioToolsQuotationMakerRoute
  StudioToolsReviewWidgetRoute: typeof StudioToolsReviewWidgetRoute
  StudioToolsSocialPostSizesRoute: typeof StudioToolsSocialPostSizesRoute
  StudioToolsSocialWallRoute: typeof StudioToolsSocialWallRoute
  StudioToolsTermsGeneratorRoute: typeof StudioToolsTermsGeneratorRoute
  StudioToolsTrustpilotIntegrationRoute: typeof StudioToolsTrustpilotIntegrationRoute
  StudioToolsUtmBuilderRoute: typeof StudioToolsUtmBuilderRoute
  StudioToolsVatCalculatorRoute: typeof StudioToolsVatCalculatorRoute
  StudioWorkSlugRoute: typeof StudioWorkSlugRoute
  StudioBlogIndexRoute: typeof StudioBlogIndexRoute
  StudioTemplatesIndexRoute: typeof StudioTemplatesIndexRoute
  StudioToolsIndexRoute: typeof StudioToolsIndexRoute
  StudioWorkIndexRoute: typeof StudioWorkIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioSplatRoute: StudioSplatRoute,
  StudioAboutRoute: StudioAboutRoute,
  StudioContactRoute: StudioContactRoute,
  StudioIllustrationsRoute: StudioIllustrationsRoute,
  StudioLovableSavingsRoute: StudioLovableSavingsRoute,
  StudioProjectPlannerRoute: StudioProjectPlannerRoute,
  StudioSkillsRoute: StudioSkillsRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioBlogDundalkSeoGuideRoute: StudioBlogDundalkSeoGuideRoute,
  StudioServicesServiceRoute: StudioServicesServiceRoute,
  StudioTemplatesTakeawayHubRoute: StudioTemplatesTakeawayHubRoute,
  StudioToolsBookingsDemosRoute: StudioToolsBookingsDemosRoute,
  StudioToolsBusinessNameGeneratorRoute: StudioToolsBusinessNameGeneratorRoute,
  StudioToolsChatLeadCaptureRoute: StudioToolsChatLeadCaptureRoute,
  StudioToolsCookieConsentManagerRoute: StudioToolsCookieConsentManagerRoute,
  StudioToolsEmailSignatureRoute: StudioToolsEmailSignatureRoute,
  StudioToolsHashtagSuggesterRoute: StudioToolsHashtagSuggesterRoute,
  StudioToolsInvoiceCreatorRoute: StudioToolsInvoiceCreatorRoute,
  StudioToolsOpengraphPreviewRoute: StudioToolsOpengraphPreviewRoute,
  StudioToolsPasswordGeneratorRoute: StudioToolsPasswordGeneratorRoute,
  StudioToolsPopupOfferEngineRoute: StudioToolsPopupOfferEngineRoute,
  StudioToolsPrivacyPolicyBuilderRoute: StudioToolsPrivacyPolicyBuilderRoute,
  StudioToolsQrCodeGeneratorRoute: StudioToolsQrCodeGeneratorRoute,
  StudioToolsQuotationMakerRoute: StudioToolsQuotationMakerRoute,
  StudioToolsReviewWidgetRoute: StudioToolsReviewWidgetRoute,
  StudioToolsSocialPostSizesRoute: StudioToolsSocialPostSizesRoute,
  StudioToolsSocialWallRoute: StudioToolsSocialWallRoute,
  StudioToolsTermsGeneratorRoute: StudioToolsTermsGeneratorRoute,
  StudioToolsTrustpilotIntegrationRoute: StudioToolsTrustpilotIntegrationRoute,
  StudioToolsUtmBuilderRoute: StudioToolsUtmBuilderRoute,
  StudioToolsVatCalculatorRoute: StudioToolsVatCalculatorRoute,
  StudioWorkSlugRoute: StudioWorkSlugRoute,
  StudioBlogIndexRoute: StudioBlogIndexRoute,
  StudioTemplatesIndexRoute: StudioTemplatesIndexRoute,
  StudioToolsIndexRoute: StudioToolsIndexRoute,
  StudioWorkIndexRoute: StudioWorkIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StudioRoute: StudioRouteWithChildren,
  FunRoute: FunRoute,
  ApiSitemapAuditRoute: ApiSitemapAuditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
